# GitHub Pages Configuration
title: AI Smart Unit Converter
description: A modern, drag-and-drop unit converter with 15+ categories and 120+ units
url: "https://yourusername.github.io/your-repo-name"
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - README.md
  - .gitignore
  - .github 